export const SET_GAME_STATUS = "SET_GAME_STATUS";
export const UPDATE_CELL_MAP = "UPDATE_CELL_MAP";
export const INCREMENT_MOVES = "INCREMENT_MOVES";
export const UPDATE_PLAYER_TURN = "UPDATE_PLAYER_TURN";
